<div class="container-fluid">
  <div class="row banner-home">
    <div class="col-md-3">
      <img src="https://c2.staticflickr.com/6/5105/5626762538_406270541c_b.jpg">
    </div>
    <div class="col-md-9">
      <h1>Il cioccolato più buono? Lo trovi da noi!</h1>
    </div>
  </div>
  <div class="row">

      <?php /* foreach($this->prodottiEvidenza as $prodotto) {
          echo $this->partial('partials/prodotto.phtml', ['prodotto' => $prodotto]);
      } */?>
      <p>qweqweqweqwe</p><br/>
      <p>asdasdsad</p><br/>
      <p>zxczxcxzc</p><br/>
      <p>123132132</p><br/>
      <p>654654654</p><br/>


  </div>
</div>
