<html>
  <head>
    <title>Sample "Hello, World" Application</title>
  </head>
  <body bgcolor=white>

    <table border="0" cellpadding="10">
      <tr>
        <td>
          <img src="http://www.fpamelard.fr/IMG/png/logo-zend-framework-50.png">
        </td>
        <td>
          <h1>Sample "Hello, World" Application</h1>
        </td>
      </tr>
    </table>

    <p>This is the home page for the HelloWorld Web application. </p>
    <p>To prove that they work, you can execute either of the following links:
    <ul>
      <li>To <a href="<?=$this->url('application/istruzioni')?>">Istruzioni</a>.
      <li>To <a href="http://www.google.com/ncr">GoOgLe</a>.
    </ul>

  </body>
</html>
