<div class="col-sm-6 col-sm-offset-1">
        <p>Horizontal form</p>
        <form class="form-horizontal">
          <div class="form-group">
            <label class="col-sm-3 control-label" for="form-horizontal-testo">Testo</label>
            <div class="col-sm-9">
              <input class="form-control" id="form-horizontal-testo" type="text">
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label">Label</label>
            <div class="col-sm-9">
              <p class="form-control-static">Testo statico</p>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label" for="form-horizontal-email">Email</label>
            <div class="col-sm-9">
              <input class="form-control" id="form-horizontal-email" type="email">
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label" for="form-horizontal-password">Password</label>
            <div class="col-sm-9">
              <input class="form-control" id="form-horizontal-password" type="password">
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label" for="form-horizontal-select">Select</label>
            <div class="col-sm-9">
              <select class="form-control" id="form-horizontal-select">
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
              </select>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label" for="form-horizontal-textarea">Textarea</label>
            <div class="col-sm-9">
              <textarea class="form-control" id="form-horizontal-textarea" rows="5"></textarea>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label" for="form-horizontal-file">Document</label>
            <div class="col-sm-9">
              <input id="form-horizontal-file" type="file">
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label">Checkbox</label>
            <div class="col-sm-9">
              <div class="checkbox">
                <label>
                  <input type="checkbox">
                  Distinctio in inventore praesentium perspiciatis
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <input type="checkbox">
                  Distinctio in inventore praesentium perspiciatis
                </label>
              </div>
              <div class="checkbox disabled">
                <label>
                  <input disabled="disabled" type="checkbox">
                  Quam quia, dolore maxime
                </label>
              </div>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label">Radio</label>
            <div class="col-sm-9">
              <div class="radio">
                <label>
                  <input name="radio-group-horizontal" type="radio">
                  Quos quo mollitia quas totam rerum velit
                </label>
              </div>
              <div class="radio">
                <label>
                  <input name="radio-group-horizontal" type="radio">
                  Quos quo mollitia quas totam rerum velit
                </label>
              </div>
              <div class="radio">
                <label>
                  <input name="radio-group-horizontal" type="radio">
                  Quos quo mollitia quas totam rerum velit
                </label>
              </div>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label">Checkbox inline</label>
            <div class="col-sm-9">
              <label class="checkbox-inline">
                <input type="checkbox">
                Sì
              </label>
              <label class="checkbox-inline">
                <input type="checkbox">
                No
              </label>
              <label class="checkbox-inline disabled">
                <input disabled="disabled" type="checkbox">
                Boh
              </label>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label">Radio inline</label>
            <div class="col-sm-9">
              <label class="radio-inline">
                <input name="radio-group-horizontal-inline" type="radio">
                Uno
              </label>
              <label class="radio-inline">
                <input name="radio-group-horizontal-inline" type="radio">
                Due
              </label>
              <label class="radio-inline">
                <input name="radio-group-horizontal-inline" type="radio">
                Tre
              </label>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
              <button class="btn btn-primary" type="submit">Submit</button>
            </div>
          </div>
        </form>
      </div>
